version: "3.8"
services:

  db-mongo:
    image: mongo
    container_name: mongoDB
    restart: always
    depends_on:
      - nodeJS
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017

